### ISSUE TITLE
Lag on join

### ISSUE THREAD

**Issue by confuser** [OhBlihv/BlivTrails#1]
https://github.com/OhBlihv/BlivTrails/blob/master/src/main/java/net/auscraft/BlivTrails/TrailListener.java#L1233

MySQL queries and other i/o operations should not be ran on the main thread, otherwise it'll cause lock ups on the main thread whilst it awaits a response.

**Comment by OhBlihv** [comment]
Yep, will add asynchronous mysql loading/saving into an upcoming update.

Thanks for the report.
