### ISSUE TITLE
Internal Error 

### ISSUE THREAD

**Issue by DDematto** [OhBlihv/BlivTrails#5]
This is on Version: 

29.03 17:39:36 [Server] INFO This server is running Thermos | https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.46 (MC: 1.7.10)

29.03 17:37:59 [Server] INFO timberghost issued server command: /trails
29.03 17:37:59 [Server] ERROR null
29.03 17:37:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'trails' in plugin BlivTrails v1.1.1
29.03 17:37:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.46]
29.03 17:37:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.46]
29.03 17:37:59 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1614.46]
29.03 17:37:59 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
29.03 17:37:59 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
29.03 17:37:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
29.03 17:37:59 [Server] INFO Caused by: java.lang.NullPointerException
29.03 17:37:59 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[ItemStack.class:1.7.10-1614.46]
29.03 17:37:59 [Server] INFO at net.auscraft.BlivTrails.TrailListener.menuItem(TrailListener.java:1930) ~[?:?]
29.03 17:37:59 [Server] INFO at net.auscraft.BlivTrails.TrailListener.mainMenu(TrailListener.java:677) ~[?:?]
29.03 17:37:59 [Server] INFO at net.auscraft.BlivTrails.TrailCommand.onCommand(TrailCommand.java:33) ~[?:?]
29.03 17:37:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.46]
29.03 17:37:59 [Server] INFO ... 13 more

**Comment by OhBlihv** [comment]
High chance you have a material that doesn't exist at your version.
Take a look through your config for anything that isn't in Vanilla 1.7.10.

Take note BlivTrails doesn't support any server mods, which might be the main culprit here.

**Comment by DDematto** [comment]
Could I Pay for you to get this to work with my server?

**Comment by OhBlihv** [comment]
Send me your config and what you want to work, and I'll see what I can do.

**Comment by OhBlihv** [comment]
Give the newest update a try, since you're running a variant of 1.7.10, this may work.
https://www.spigotmc.org/resources/blivtrails.4544/update?update=80046

If not, I'll work on a fix.

**Comment by DDematto** [comment]
http://pastie.org/10780981

We Can Now do /trails however no one Sees any particles.
Configs Were never changed

**Comment by OhBlihv** [comment]
Seems like Thermos has a weird way of storing/integrating with the Vanilla Minecraft Server.
I'll take a look around their source and see how they're doing it.

**Comment by DDematto** [comment]
Allow me to Help: Im seeing this but i dont know what its about 

http://dev.bukkit.org/bukkit-plugins/effectlib/

Apparently Some Man got it to work With his Particle plugin

**Comment by OhBlihv** [comment]
Give https://github.com/OhBlihv/BlivTrails/releases/tag/1.1.2a a try.
I was doing the Thermos support by hand yesterday - and that took about 1-2 hours to get just the initial setup done.

That link has the same approach, and effectively finished it off for me.

**Comment by DDematto** [comment]
Yup it is Working :D 
![2016-04-02_09 32 40](https://cloud.githubusercontent.com/assets/12821048/14226662/f0c4060e-f8b5-11e5-904a-7ca2d9be7bfb.png)

**Comment by Brend-Smits** [comment]
This update is amazing! Thanks a lot for supporting Thermos @OhBlihv !
1 small error though: https://gyazo.com/25ff81b329e2b7245f7c7be8819aa202
When using Barrier.
Everything else works perfectly!

**Comment by OhBlihv** [comment]
@Rubbertjuh 
Barrier isn't supported on 1.7.10 (Its a 1.8 particle).
I've added some warnings about the default config containing 1.8 particles/materials, but I probably should remove/comment them out entirely to avoid issues like this.

**Comment by Brend-Smits** [comment]
Maybe that would be a good idea indeed :)
Wonderful job @OhBlihv very excited about this!
